import { chmod, mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { dirname } from 'node:path';
import { paths } from './paths';
import type { AppConfig, AppPreferences, TenantBrand } from './schema';
import { secretKeyForApp } from './schema';
import { initialBackendProfiles } from '../agent/profiles';

export async function loadConfig(path: string = paths.configFile): Promise<Partial<AppConfig>> {
  try {
    const text = await readFile(path, 'utf8');
    return JSON.parse(text) as Partial<AppConfig>;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {};
    throw err;
  }
}

/**
 * Build an AppConfig whose secret is an exec-provider SecretRef pointing at
 * the local keystore via the secrets-getter wrapper. Bridge short-circuits
 * the spawn and reads the keystore directly; lark-cli can read the same way.
 */
export async function buildEncryptedAccountConfig(
  appId: string,
  tenant: TenantBrand,
  preferences?: AppPreferences,
): Promise<AppConfig> {
  const wrapperPath = await ensureSecretsGetterWrapper();
  return {
    accounts: {
      app: {
        id: appId,
        secret: { source: 'exec', provider: 'bridge', id: secretKeyForApp(appId) },
        tenant,
      },
    },
    secrets: {
      providers: {
        bridge: { source: 'exec', command: wrapperPath, args: [] },
      },
    },
    backendProfiles: initialBackendProfiles(),
    ...(preferences ? { preferences } : {}),
  };
}

/**
 * Write the secrets-getter wrapper pointing at the current node + bridge
 * entry. Always rewrites (node path can move). 0700 perms.
 */
export async function ensureSecretsGetterWrapper(): Promise<string> {
  const wrapperPath = paths.secretsGetterScript;
  const node = process.execPath;
  const bridgeEntry = process.argv[1] ?? '';
  const sq = (s: string): string => `'${s.replace(/'/g, `'\\''`)}'`;
  const content =
    `#!/bin/sh\n` +
    `# Auto-generated by feishu-codex-bridge. Do not edit.\n` +
    `exec ${sq(node)} ${sq(bridgeEntry)} secrets get "$@"\n`;
  await mkdir(dirname(wrapperPath), { recursive: true });
  const tmp = `${wrapperPath}.tmp-${process.pid}`;
  await writeFile(tmp, content, 'utf8');
  await chmod(tmp, 0o700);
  await rename(tmp, wrapperPath);
  return wrapperPath;
}

// 同进程内并发 saveConfig 串行化 + tmp 唯一名：避免两次写共用 tmp 文件交错（rename
// 命中被对方写一半的 tmp → JSON 损坏，或丢写）。
let saveChain: Promise<unknown> = Promise.resolve();
export function saveConfig(cfg: AppConfig, path: string = paths.configFile): Promise<void> {
  const run = saveChain.then(async () => {
    await mkdir(dirname(path), { recursive: true });
    const tmp = `${path}.tmp-${process.pid}-${randomUUID()}`;
    await writeFile(tmp, `${JSON.stringify(cfg, null, 2)}\n`, 'utf8');
    await chmod(tmp, 0o600);
    await rename(tmp, path);
  });
  saveChain = run.then(
    () => undefined,
    () => undefined,
  );
  return run;
}
